### ISSUE TITLE
trans_gen on Windows 10 - panic path issue

### ISSUE THREAD

**Issue by foreachthing** [sumatrapdfreader/sumatrapdf#1648]
I'm adding some buttons to the toolbar and wanted to translate the text.

So, I've installed `go` and ran `doit.bat`.
This this message appeared:

![image](https://user-images.githubusercontent.com/10420187/85976685-57c92d80-b9db-11ea-9336-751ec6facdae.png)

How can I fix this `panic` path issue?

**Comment by kjk** [comment]
The directory must be `sumatrapdf` (not `sumatrapdf_2019`). Or you can change `u.CdUpDir("sumatrapdf")` in main.go to your directory name.
`

**Comment by foreachthing** [comment]
doh!
Thanks, @kjk !

**Comment by foreachthing** [comment]
I got another one, that fits in here:

```
C:\dev\sumatrapdf\do>do.exe -trans-regen
Current directory: C:\dev\sumatrapdf
generate_code
293 strings
Files to process: 82
368 strings to translate
Removed 1 obsolete strings
gen_c_code_for_dir: 'src', 292 strings, len(strings_dict): 292
g_incomplete_langs: 10
langs: 61, g_langs: 71
langcodes: 677 bytes
langnames: 2982 bytes
langids: 1833 bytes
translations_refs: 1274 bytes
translations: 1426096 bytes
Finished in 573.0015ms
panic: template: tmpl:5:2: executing "tmpl" at <.Translations_refs>: can't evaluate field Translations_refs in type struct { TranslationsRefs string; Translations string }

goroutine 1 [running]:
github.com/kjk/u.Must(0xa85c60, 0xc0003f8020)
        C:/Users/USERNAME/go/pkg/mod/github.com/kjk/u@v0.0.0-20191229080709-d1ac8976d53f/util.go:22 +0x51
main.evalTmpl(0x9d7b84, 0xb4, 0x939680, 0xc000114700, 0x1, 0xc001660500)
        C:/dev/sumatrapdf/do/util.go:220 +0x114
main.genCCodeForDir(0xc0001a2120, 0xc000090000, 0x124, 0x200, 0x9ac35b, 0x3)
        C:/dev/sumatrapdf/do/trans_gen.go:363 +0x11da
main.genCCode(0xc0001a2120, 0xc000112000, 0x170, 0x200)
        C:/dev/sumatrapdf/do/trans_gen.go:421 +0x323
main.generateCode(0xc0002c2000, 0xa020d)
        C:/dev/sumatrapdf/do/translations.go:318 +0x529
main.regenerateLangs()
        C:/dev/sumatrapdf/do/translations.go:349 +0xea
main.main()
        C:/dev/sumatrapdf/do/main.go:280 +0x17fc

C:\dev\sumatrapdf\do>
```

This line here, `C:/Users/USERNAME/go/pkg/mod/github.com/kjk/u@v0.0.0-20191229080709-d1ac8976d53f/util.go:22 +0x51`, with my username ... I don't get it. This path does not exist. Am I supposed to create it?

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/c91bd16ae3ce2e64e9516465daad8889e0c58489
