### ISSUE TITLE
How to translate new string?

### ISSUE THREAD

**Issue by foreachthing** [sumatrapdfreader/sumatrapdf#1663]
I'm adding a few new buttons to the toolbar and am struggling with the translation process.

I updated the translation.txt and now, as far as I can tell, need to run do.sh:

```
user@machine MINGW64 /c/dev/sumatrapdf/do (master)
$ ./do.sh -trans-regen
Current directory: C:\dev\sumatrapdf
generate_code
Finished in 15.003ms
panic: condition failed

goroutine 1 [running]:
github.com/kjk/u.PanicIf(0xc000315c01, 0x0, 0x0, 0x0)
        C:/Users/USERNAME/go/pkg/mod/github.com/kjk/u@v0.0.0-20191229080709-d1ac8976d53f/util.go:42 +0x13b
main.parseTranslations(0xc0002c2000, 0xa0457, 0xc00021fcc8)
        C:/dev/sumatrapdf/do/translations.go:135 +0x3a4
main.generateCode(0xc0002c2000, 0xa0457)
        C:/dev/sumatrapdf/do/translations.go:289 +0xbb
main.regenerateLangs()
        C:/dev/sumatrapdf/do/translations.go:349 +0xea
main.main()
        C:/dev/sumatrapdf/do/main.go:280 +0x17fc
exit status 2
```

What am I missing?
Thanks!

**Comment by kjk** [comment]
The exception implies that `translations.txt` file has invalid line.
Briefly, the format is:
```
:string 1 to translate
es:spanish translation
de:german translation
:string 2 to translate
es:spanish translation
```
I've added a more descriptive error message for this panic.

**Comment by foreachthing** [comment]
Excellent!
Thanks a bunch!
