### ISSUE TITLE
DDEMLException: A transaction has failed.

### ISSUE THREAD

**Issue by PHPirates** [sumatrapdfreader/sumatrapdf#2116]
We have had the following crash, reproducible (but I think not consistently) by at least one user:

```
Caused by: com.pretty_tools.dde.DDEMLException: A transaction has failed.
	at com.pretty_tools.dde.client.DDEClientConversation.nativeExecute(Native Method)
	at com.pretty_tools.dde.client.DDEClientConversation.execute(DDEClientConversation.java:133)
	at nl.hannahsten.texifyidea.run.sumatra.SumatraConversation.execute(SumatraConversation.kt:132)
```

The user is using version 3.3.3.

We are just [executing DDE commands](https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/master/src/nl/hannahsten/texifyidea/run/sumatra/SumatraConversation.kt) which work pretty much always, any idea what could be wrong here?
I could not reproduce this issue myself.

**Comment by GitHubRulesOK** [comment]
"Connection to SumatraPDF was disrupted." starts the reported chain ?
I see there is a catch all after comprehensive tests for SumatraPDF either registered or on path or possibly in a Portable folder 
But could still potentially be defeated if not then running as a DDE service after all that.

Also at a first glance I did not see any platform test for any 32bit/64bit mismatch (if texify has 32 bit dependency for the DDE call it would be wise to install 32bit SumatraPDF)

**Comment by PHPirates** [comment]
That's us catching and rethrowing the exception indeed. We are including both JavaDDE.dll and JavaDDEx64.dll for JDDE to use, but I'm not sure if we depend on Sumatra being 32 or 64 bit or what we should do with it. Both versions work for me anyway.

Do you have any idea if we could get a more detailed error log from Sumatra, or is this a problem in JDDE?

**Comment by GitHubRulesOK** [comment]
I just update to say my **guess** is timing,
For client tests is it possible to inject a small delay or get them to test with SumatraPDF standing by.

**Comment by PHPirates** [comment]
What do you mean exactly? That we should build in a small delay in sending messages?
Given that this problem is a very rare occurrence, it could well be timing related.

**Comment by GitHubRulesOK** [comment]
When the DDE call is transmitted if a slow machine has not loaded SumatraPDF to be broadcasting its service ability the call could fail. I personally advocate cli calling to avoid that potential scenario, however the SumatraPDF dev (rightly) advocates using DDE as robust in its own right :-) it is up to 3rd parties to be aware.

**Comment by PHPirates** [comment]
Ah, yeah that's indeed a possible explanation. Maybe I'll just assume that your guess is right and create a possible workaround, and then see if the issue comes back. Thanks for your help!

**Comment by kjk** [comment]
The error is not coming from Sumatra (or at least there's no evidence it's coming from Sumatra).
